name: Build MediaPipe on macOS with Metal

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows you to manually trigger from the Actions tab

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew update
        brew install bazelisk protobuf cmake ffmpeg

    - name: Build holistic_tracking_gpu with Metal
      run: |
        bazel clean --expunge
        bazel build -c opt \
          --enable_workspace=true \
          --repo_env=HERMETIC_PYTHON_VERSION=3.12 \
          --experimental_repo_remote_exec \
          --python_path=/usr/bin/python3 \
          --force_python=py3 \
          --define MEDIAPIPE_DISABLE_GPU=0 \
          --copt=-DMEDIAPIPE_METAL_ENABLED \
          --copt=-DMEDIAPIPE_GPU_USE_METAL \
          mediapipe/examples/desktop/holistic_tracking:holistic_tracking_gpu

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: holistic_tracking_gpu
        path: bazel-bin/mediapipe/examples/desktop/holistic_tracking/holistic_tracking_gpu
